# Generated by Django 4.2 on 2025-06-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("license_plate", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=20)),
                ("issued_date", models.DateField()),
                ("expired_date", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="vehiclehistory",
            name="vehicle",
        ),
        migrations.DeleteModel(
            name="UserVehicle",
        ),
        migrations.DeleteModel(
            name="VehicleHistory",
        ),
    ]
