# Generated by Django 4.2 on 2025-06-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plates", "0002_vehicle_remove_vehiclehistory_vehicle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("action", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("image", models.TextField(blank=True)),
            ],
        ),
    ]
