# Generated by Django 4.2 on 2025-06-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plates", "0003_history"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="history",
            name="action",
        ),
        migrations.RemoveField(
            model_name="history",
            name="image",
        ),
        migrations.RemoveField(
            model_name="history",
            name="status",
        ),
        migrations.AddField(
            model_name="history",
            name="checkin_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="checkout_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="entry_status",
            field=models.CharField(
                choices=[("inlot", "In Lot"), ("done", "Done")],
                default="inlot",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="history",
            name="model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("unregistered", "Unregistered"),
                ],
                default="unregistered",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="history",
            name="unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="history",
            name="user_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
