# Generated by Django 4.2 on 2025-06-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plates", "0004_rename_timestamp_history_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="History",
        ),
    ]
