# Generated by Django 4.2 on 2025-06-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plates", "0007_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="vehicle_avatars/"
            ),
        ),
    ]
